# Generated by Django 4.0.6 on 2022-07-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('product_code', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
