# Generated by Django 4.0.6 on 2022-08-01 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('addr_line1', models.CharField(max_length=100)),
                ('addr_line2', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('qty', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled')], max_length=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
